2022-12-03 11:09:19.849 [info] Extension host agent started.
2022-12-03 11:09:26.052 [info] [127.0.0.1][e9e2d287][ManagementConnection] New connection established.
2022-12-03 11:09:26.065 [info] [127.0.0.1][1deb300e][ExtensionHostConnection] New connection established.
2022-12-03 11:09:26.121 [info] [127.0.0.1][1deb300e][ExtensionHostConnection] <1341> Launched Extension Host Process.
2022-12-03 11:09:30.686 [error] Error: Unexpected SIGPIPE
    at process.<anonymous> (/home/lab4bardadymso/.vscode-server/bin/6261075646f055b99068d3688932416f2346dd3b/out/vs/server/node/server.main.js:154:7913)
    at process.emit (node:events:526:28)
2022-12-03 11:33:59.707 [info] [127.0.0.1][e9e2d287][ManagementConnection] The client has disconnected gracefully, so the connection will be disposed.
2022-12-03 11:34:00.909 [info] [127.0.0.1][1deb300e][ExtensionHostConnection] <1341> Extension Host Process exited with code: 0, signal: null.
2022-12-03 11:34:00.913 [info] Last EH closed, waiting before shutting down
2022-12-03 11:34:08.324 [info] Got delay-shutdown request while in shutdown timeout, delaying
2022-12-03 11:34:08.325 [info] Cancelling previous shutdown timeout
2022-12-03 11:34:08.595 [info] [127.0.0.1][e75a3fd6][ManagementConnection] New connection established.
2022-12-03 11:34:08.602 [info] [127.0.0.1][336ecc91][ExtensionHostConnection] New connection established.
2022-12-03 11:34:08.656 [info] [127.0.0.1][336ecc91][ExtensionHostConnection] <4487> Launched Extension Host Process.
2022-12-03 11:34:11.429 [error] CodeExpectedError: Could not find pty on pty host
    at d._throwIfNoPty (/home/lab4bardadymso/.vscode-server/bin/6261075646f055b99068d3688932416f2346dd3b/out/vs/platform/terminal/node/ptyHostMain.js:27:7199)
    at d.updateTitle (/home/lab4bardadymso/.vscode-server/bin/6261075646f055b99068d3688932416f2346dd3b/out/vs/platform/terminal/node/ptyHostMain.js:27:2931)
    at Object.call (/home/lab4bardadymso/.vscode-server/bin/6261075646f055b99068d3688932416f2346dd3b/out/vs/platform/terminal/node/ptyHostMain.js:17:5858)
    at s.onPromise (/home/lab4bardadymso/.vscode-server/bin/6261075646f055b99068d3688932416f2346dd3b/out/vs/platform/terminal/node/ptyHostMain.js:15:5833)
    at s.onRawMessage (/home/lab4bardadymso/.vscode-server/bin/6261075646f055b99068d3688932416f2346dd3b/out/vs/platform/terminal/node/ptyHostMain.js:15:5216)
    at /home/lab4bardadymso/.vscode-server/bin/6261075646f055b99068d3688932416f2346dd3b/out/vs/platform/terminal/node/ptyHostMain.js:15:4502
    at r.invoke (/home/lab4bardadymso/.vscode-server/bin/6261075646f055b99068d3688932416f2346dd3b/out/vs/platform/terminal/node/ptyHostMain.js:11:145)
    at P.deliver (/home/lab4bardadymso/.vscode-server/bin/6261075646f055b99068d3688932416f2346dd3b/out/vs/platform/terminal/node/ptyHostMain.js:11:2275)
    at w.fire (/home/lab4bardadymso/.vscode-server/bin/6261075646f055b99068d3688932416f2346dd3b/out/vs/platform/terminal/node/ptyHostMain.js:11:1853)
    at process.M (/home/lab4bardadymso/.vscode-server/bin/6261075646f055b99068d3688932416f2346dd3b/out/vs/platform/terminal/node/ptyHostMain.js:9:21066)
    at process.emit (node:events:526:28)
    at emit (node:internal/child_process:938:14)
    at processTicksAndRejections (node:internal/process/task_queues:84:21)
2022-12-03 11:34:17.057 [error] CodeExpectedError: Could not find pty on pty host
    at d._throwIfNoPty (/home/lab4bardadymso/.vscode-server/bin/6261075646f055b99068d3688932416f2346dd3b/out/vs/platform/terminal/node/ptyHostMain.js:27:7199)
    at d.updateIcon (/home/lab4bardadymso/.vscode-server/bin/6261075646f055b99068d3688932416f2346dd3b/out/vs/platform/terminal/node/ptyHostMain.js:27:2993)
    at Object.call (/home/lab4bardadymso/.vscode-server/bin/6261075646f055b99068d3688932416f2346dd3b/out/vs/platform/terminal/node/ptyHostMain.js:17:5858)
    at s.onPromise (/home/lab4bardadymso/.vscode-server/bin/6261075646f055b99068d3688932416f2346dd3b/out/vs/platform/terminal/node/ptyHostMain.js:15:5833)
    at s.onRawMessage (/home/lab4bardadymso/.vscode-server/bin/6261075646f055b99068d3688932416f2346dd3b/out/vs/platform/terminal/node/ptyHostMain.js:15:5216)
    at /home/lab4bardadymso/.vscode-server/bin/6261075646f055b99068d3688932416f2346dd3b/out/vs/platform/terminal/node/ptyHostMain.js:15:4502
    at r.invoke (/home/lab4bardadymso/.vscode-server/bin/6261075646f055b99068d3688932416f2346dd3b/out/vs/platform/terminal/node/ptyHostMain.js:11:145)
    at P.deliver (/home/lab4bardadymso/.vscode-server/bin/6261075646f055b99068d3688932416f2346dd3b/out/vs/platform/terminal/node/ptyHostMain.js:11:2275)
    at w.fire (/home/lab4bardadymso/.vscode-server/bin/6261075646f055b99068d3688932416f2346dd3b/out/vs/platform/terminal/node/ptyHostMain.js:11:1853)
    at process.M (/home/lab4bardadymso/.vscode-server/bin/6261075646f055b99068d3688932416f2346dd3b/out/vs/platform/terminal/node/ptyHostMain.js:9:21066)
    at process.emit (node:events:526:28)
    at emit (node:internal/child_process:938:14)
    at processTicksAndRejections (node:internal/process/task_queues:84:21)
2022-12-03 11:34:17.058 [error] CodeExpectedError: Could not find pty on pty host
    at d._throwIfNoPty (/home/lab4bardadymso/.vscode-server/bin/6261075646f055b99068d3688932416f2346dd3b/out/vs/platform/terminal/node/ptyHostMain.js:27:7199)
    at d.updateTitle (/home/lab4bardadymso/.vscode-server/bin/6261075646f055b99068d3688932416f2346dd3b/out/vs/platform/terminal/node/ptyHostMain.js:27:2931)
    at Object.call (/home/lab4bardadymso/.vscode-server/bin/6261075646f055b99068d3688932416f2346dd3b/out/vs/platform/terminal/node/ptyHostMain.js:17:5858)
    at s.onPromise (/home/lab4bardadymso/.vscode-server/bin/6261075646f055b99068d3688932416f2346dd3b/out/vs/platform/terminal/node/ptyHostMain.js:15:5833)
    at s.onRawMessage (/home/lab4bardadymso/.vscode-server/bin/6261075646f055b99068d3688932416f2346dd3b/out/vs/platform/terminal/node/ptyHostMain.js:15:5216)
    at /home/lab4bardadymso/.vscode-server/bin/6261075646f055b99068d3688932416f2346dd3b/out/vs/platform/terminal/node/ptyHostMain.js:15:4502
    at r.invoke (/home/lab4bardadymso/.vscode-server/bin/6261075646f055b99068d3688932416f2346dd3b/out/vs/platform/terminal/node/ptyHostMain.js:11:145)
    at P.deliver (/home/lab4bardadymso/.vscode-server/bin/6261075646f055b99068d3688932416f2346dd3b/out/vs/platform/terminal/node/ptyHostMain.js:11:2275)
    at w.fire (/home/lab4bardadymso/.vscode-server/bin/6261075646f055b99068d3688932416f2346dd3b/out/vs/platform/terminal/node/ptyHostMain.js:11:1853)
    at process.M (/home/lab4bardadymso/.vscode-server/bin/6261075646f055b99068d3688932416f2346dd3b/out/vs/platform/terminal/node/ptyHostMain.js:9:21066)
    at process.emit (node:events:526:28)
    at emit (node:internal/child_process:938:14)
    at processTicksAndRejections (node:internal/process/task_queues:84:21)
2022-12-03 11:39:08.330 [info] New EH opened, aborting shutdown
2022-12-03 12:21:15.548 [warning] No ptyHost heartbeat after 6 seconds
2022-12-03 12:21:49.522 [info] [127.0.0.1][e75a3fd6][ManagementConnection] The client has reconnected.
2022-12-03 12:21:49.525 [info] [127.0.0.1][336ecc91][ExtensionHostConnection] The client has reconnected.
2022-12-03 12:21:50.750 [error] CodeExpectedError: Could not find pty on pty host
    at d._throwIfNoPty (/home/lab4bardadymso/.vscode-server/bin/6261075646f055b99068d3688932416f2346dd3b/out/vs/platform/terminal/node/ptyHostMain.js:27:7199)
    at d.updateIcon (/home/lab4bardadymso/.vscode-server/bin/6261075646f055b99068d3688932416f2346dd3b/out/vs/platform/terminal/node/ptyHostMain.js:27:2993)
    at Object.call (/home/lab4bardadymso/.vscode-server/bin/6261075646f055b99068d3688932416f2346dd3b/out/vs/platform/terminal/node/ptyHostMain.js:17:5858)
    at s.onPromise (/home/lab4bardadymso/.vscode-server/bin/6261075646f055b99068d3688932416f2346dd3b/out/vs/platform/terminal/node/ptyHostMain.js:15:5833)
    at s.onRawMessage (/home/lab4bardadymso/.vscode-server/bin/6261075646f055b99068d3688932416f2346dd3b/out/vs/platform/terminal/node/ptyHostMain.js:15:5216)
    at /home/lab4bardadymso/.vscode-server/bin/6261075646f055b99068d3688932416f2346dd3b/out/vs/platform/terminal/node/ptyHostMain.js:15:4502
    at r.invoke (/home/lab4bardadymso/.vscode-server/bin/6261075646f055b99068d3688932416f2346dd3b/out/vs/platform/terminal/node/ptyHostMain.js:11:145)
    at P.deliver (/home/lab4bardadymso/.vscode-server/bin/6261075646f055b99068d3688932416f2346dd3b/out/vs/platform/terminal/node/ptyHostMain.js:11:2275)
    at w.fire (/home/lab4bardadymso/.vscode-server/bin/6261075646f055b99068d3688932416f2346dd3b/out/vs/platform/terminal/node/ptyHostMain.js:11:1853)
    at process.M (/home/lab4bardadymso/.vscode-server/bin/6261075646f055b99068d3688932416f2346dd3b/out/vs/platform/terminal/node/ptyHostMain.js:9:21066)
    at process.emit (node:events:526:28)
    at emit (node:internal/child_process:938:14)
    at processTicksAndRejections (node:internal/process/task_queues:84:21)
2022-12-03 12:21:50.763 [error] CodeExpectedError: Could not find pty on pty host
    at d._throwIfNoPty (/home/lab4bardadymso/.vscode-server/bin/6261075646f055b99068d3688932416f2346dd3b/out/vs/platform/terminal/node/ptyHostMain.js:27:7199)
    at d.updateTitle (/home/lab4bardadymso/.vscode-server/bin/6261075646f055b99068d3688932416f2346dd3b/out/vs/platform/terminal/node/ptyHostMain.js:27:2931)
    at Object.call (/home/lab4bardadymso/.vscode-server/bin/6261075646f055b99068d3688932416f2346dd3b/out/vs/platform/terminal/node/ptyHostMain.js:17:5858)
    at s.onPromise (/home/lab4bardadymso/.vscode-server/bin/6261075646f055b99068d3688932416f2346dd3b/out/vs/platform/terminal/node/ptyHostMain.js:15:5833)
    at s.onRawMessage (/home/lab4bardadymso/.vscode-server/bin/6261075646f055b99068d3688932416f2346dd3b/out/vs/platform/terminal/node/ptyHostMain.js:15:5216)
    at /home/lab4bardadymso/.vscode-server/bin/6261075646f055b99068d3688932416f2346dd3b/out/vs/platform/terminal/node/ptyHostMain.js:15:4502
    at r.invoke (/home/lab4bardadymso/.vscode-server/bin/6261075646f055b99068d3688932416f2346dd3b/out/vs/platform/terminal/node/ptyHostMain.js:11:145)
    at P.deliver (/home/lab4bardadymso/.vscode-server/bin/6261075646f055b99068d3688932416f2346dd3b/out/vs/platform/terminal/node/ptyHostMain.js:11:2275)
    at w.fire (/home/lab4bardadymso/.vscode-server/bin/6261075646f055b99068d3688932416f2346dd3b/out/vs/platform/terminal/node/ptyHostMain.js:11:1853)
    at process.M (/home/lab4bardadymso/.vscode-server/bin/6261075646f055b99068d3688932416f2346dd3b/out/vs/platform/terminal/node/ptyHostMain.js:9:21066)
    at process.emit (node:events:526:28)
    at emit (node:internal/child_process:938:14)
    at processTicksAndRejections (node:internal/process/task_queues:84:21)
2022-12-03 12:21:50.764 [error] CodeExpectedError: Could not find pty on pty host
    at d._throwIfNoPty (/home/lab4bardadymso/.vscode-server/bin/6261075646f055b99068d3688932416f2346dd3b/out/vs/platform/terminal/node/ptyHostMain.js:27:7199)
    at d.updateIcon (/home/lab4bardadymso/.vscode-server/bin/6261075646f055b99068d3688932416f2346dd3b/out/vs/platform/terminal/node/ptyHostMain.js:27:2993)
    at Object.call (/home/lab4bardadymso/.vscode-server/bin/6261075646f055b99068d3688932416f2346dd3b/out/vs/platform/terminal/node/ptyHostMain.js:17:5858)
    at s.onPromise (/home/lab4bardadymso/.vscode-server/bin/6261075646f055b99068d3688932416f2346dd3b/out/vs/platform/terminal/node/ptyHostMain.js:15:5833)
    at s.onRawMessage (/home/lab4bardadymso/.vscode-server/bin/6261075646f055b99068d3688932416f2346dd3b/out/vs/platform/terminal/node/ptyHostMain.js:15:5216)
    at /home/lab4bardadymso/.vscode-server/bin/6261075646f055b99068d3688932416f2346dd3b/out/vs/platform/terminal/node/ptyHostMain.js:15:4502
    at r.invoke (/home/lab4bardadymso/.vscode-server/bin/6261075646f055b99068d3688932416f2346dd3b/out/vs/platform/terminal/node/ptyHostMain.js:11:145)
    at P.deliver (/home/lab4bardadymso/.vscode-server/bin/6261075646f055b99068d3688932416f2346dd3b/out/vs/platform/terminal/node/ptyHostMain.js:11:2275)
    at w.fire (/home/lab4bardadymso/.vscode-server/bin/6261075646f055b99068d3688932416f2346dd3b/out/vs/platform/terminal/node/ptyHostMain.js:11:1853)
    at process.M (/home/lab4bardadymso/.vscode-server/bin/6261075646f055b99068d3688932416f2346dd3b/out/vs/platform/terminal/node/ptyHostMain.js:9:21066)
    at process.emit (node:events:526:28)
    at emit (node:internal/child_process:938:14)
    at processTicksAndRejections (node:internal/process/task_queues:84:21)
2022-12-03 12:21:50.765 [error] CodeExpectedError: Could not find pty on pty host
    at d._throwIfNoPty (/home/lab4bardadymso/.vscode-server/bin/6261075646f055b99068d3688932416f2346dd3b/out/vs/platform/terminal/node/ptyHostMain.js:27:7199)
    at d.updateTitle (/home/lab4bardadymso/.vscode-server/bin/6261075646f055b99068d3688932416f2346dd3b/out/vs/platform/terminal/node/ptyHostMain.js:27:2931)
    at Object.call (/home/lab4bardadymso/.vscode-server/bin/6261075646f055b99068d3688932416f2346dd3b/out/vs/platform/terminal/node/ptyHostMain.js:17:5858)
    at s.onPromise (/home/lab4bardadymso/.vscode-server/bin/6261075646f055b99068d3688932416f2346dd3b/out/vs/platform/terminal/node/ptyHostMain.js:15:5833)
    at s.onRawMessage (/home/lab4bardadymso/.vscode-server/bin/6261075646f055b99068d3688932416f2346dd3b/out/vs/platform/terminal/node/ptyHostMain.js:15:5216)
    at /home/lab4bardadymso/.vscode-server/bin/6261075646f055b99068d3688932416f2346dd3b/out/vs/platform/terminal/node/ptyHostMain.js:15:4502
    at r.invoke (/home/lab4bardadymso/.vscode-server/bin/6261075646f055b99068d3688932416f2346dd3b/out/vs/platform/terminal/node/ptyHostMain.js:11:145)
    at P.deliver (/home/lab4bardadymso/.vscode-server/bin/6261075646f055b99068d3688932416f2346dd3b/out/vs/platform/terminal/node/ptyHostMain.js:11:2275)
    at w.fire (/home/lab4bardadymso/.vscode-server/bin/6261075646f055b99068d3688932416f2346dd3b/out/vs/platform/terminal/node/ptyHostMain.js:11:1853)
    at process.M (/home/lab4bardadymso/.vscode-server/bin/6261075646f055b99068d3688932416f2346dd3b/out/vs/platform/terminal/node/ptyHostMain.js:9:21066)
    at process.emit (node:events:526:28)
    at emit (node:internal/child_process:938:14)
    at processTicksAndRejections (node:internal/process/task_queues:84:21)
2022-12-03 16:26:18.519 [warning] No ptyHost heartbeat after 6 seconds
